function [ x, y ] = transformtoxy( self, A, B, force )
if nargin == 4
    fitting = force;
else
    fitting = self.dataFitting;
end
x = interp2( ...
    self.inputMatrixA, ...
    self.inputMatrixB, ...
    self.inputMatrixX, ...
    A, B, fitting);
y = interp2( ...
    self.inputMatrixA, ...
    self.inputMatrixB, ...
    self.inputMatrixY, ...
    A, B, fitting);
end
